### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ebrelsford** [CartoDB/cartodb-python#12]
I [got a start on this](https://github.com/ebrelsford/cartodb-python/tree/py3k) but stopped short of making oauth work since I don't currently need it. Mostly making relative imports more explicit and dealing with modules being rearranged (eg `parse_qsl` is now in `urllib.parse`). The work's all in a81422e9.

**Comment by danicarrion** [comment]
Hey, thanks a lot. This is something we'll be working on soon, so we really appreciate it.

**Comment by jgsogo** [comment]
I've sent a PR (#13) which deals with Python3 compatibility: ImportAPI seems to work ok, but there is still an issue related to OAuth.

**Comment by danicarrion** [comment]
Already merged
