### ISSUE TITLE
Unicode characters throw Error

### ISSUE THREAD

**Issue by uberdog** [CartoDB/cartodb-python#4]
Inserting text with unicode characters throws a UnicodeEncodeError:

> INSERT INTO foo (the_geom, standard_resolution_url, username, caption, created_time, link) VALUES (ST_GeomFromText('POINT(-106.388 39.64517)', 4326),'http://distilleryimage11.instagram.com/1dfcf9d863ae11e180c9123138016265_7.jpg','fernandezmaia', 'Buen día! Hoy empiezo en Golden Peak, parece que el destino hace que nieve cada vez que yo madrugo! Va a ser un laaaargo día', to_timestamp(1330613527), 'http://instagr.am/p/HokIZBrPc_/')
> Traceback (most recent call last):
>  File "cartoImport.py", line 45, in <module>
>    cl.sql(sql)
>  File "/usr/local/lib/python2.7/dist-packages/cartodb/cartodb.py", line 67, in sql
>    p = urllib.urlencode({'q': sql})
>  File "/usr/lib/python2.7/urllib.py", line 1312, in urlencode
>    v = quote_plus(str(v))
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 254: ordinal not in range(128)

**Comment by danicarrion** [comment]
dead for 2 years
